### PR TITLE
FIX: prevent page leave confirmation dialog

### PR DESCRIPTION
**Pull request by a2nt**
.cms-edit-form has class .changed on search which looks like silverstripe bug

### CODE REVIEW

**Comment by a2nt** [comment]
Some styling updates included
Screenshot from 2021-09-27 11-21-13

**Comment by a2nt** [comment]
Linter wasn't functional I have fixed it too so it will show you CSS/JS issues on yarn build

Screenshot from 2021-09-27 11-23-51

**Comment by michalkleiner** [comment]
> .cms-edit-form has class .changed on search which looks like silverstripe bug

I think it is a Silverstripe bug which would be good to have fixed upstream if you were keen on raising a PR there :)

**Comment by a2nt** [comment]
Raised an issue here: https://github.com/silverstripe/silverstripe-cms/issues/2690

**Pull request merged**
